language: python

python:
#  - "3.2"
  - "3.3"

#virtualenv:
#  system_site_packages: true

# command to install dependencies
install: "./travis-install.sh"

before_script:
  - source /home/travis/my-python3-env/bin/activate
  - export PATH="$VIRTUAL_ENV/local/bin:$PATH"

# command to run tests
script: nosetests